### ISSUE TITLE
mqtt possible?

### ISSUE THREAD

**Issue by addy38** [NerdyProjects/HousebusNode_Heatpump#1]
Hi, 
I'am searching for an solution to bring Sensostar U Counter values via wired MBus into my Homematic or Homeassistant System.
I think the most common interface for both Systems should be mqtt. 
Do you see any chance to develop the code for this?

I have no experience about Arduino, ESP..., (did former some testing with Raspi 2B) which exactly hardware you require actual for this project?

**Comment by NerdyProjects** [comment]
Thanks for you interest and message :-) This project is kind of a mess currently but I will likely do some work on it before this winter season again.

The interface implemented in the firmware here is just a protocol on top of CAN Bus  (UAVCan) - so there is no IP interface that could provide MQTT.

It would be possible to implement this by using the corresponding sensostar files on a ESP32 with wifi and adding some mqtt code that can be found in other projects...

**Comment by addy38** [comment]
Thx for the fast answer, ok, I will folllow another project which I also found in github.
Best regards
